name: matrix Demo
on: push

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v4
        with:
          node-versiopn: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
  summarize:
    needs: build
    uses: .\.github\workflows\reusable.yml