name: matrix Demo
on: push

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node-version: [12, 18, 20]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v4
        with:
          node-versiopn: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build