name: matrix Demo
on: push

jobs:
  build:
    strategy:
      matrix:
        operating system: [ubuntu-latest, windows-latest]
        node-version: [12, 14, 16]
    runs-on: ${{ matrix.operating-systems }}
    steps:
      - name: get code
        uses: actions/Checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v4
        with:
          ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run test